spring:
  application:
    name: user-management-service
  datasource:
    url: jdbc:h2:mem:user_management_db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8083